spring.application.name=springboot-error

#Spring normalmente NO lanza esta excepción:En lugar de eso usa un controlador interno llamado: BasicErrorController,Este controlador devuelve el error automáticamente.
#Por eso tu método nunca se ejecuta. para qeu funcione tus personalizacion de errores debes activar esto:
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false